CREATE TABLE `courses` (
	`id` int AUTO_INCREMENT NOT NULL,
	`slug` varchar(64) NOT NULL,
	`nameEn` varchar(255) NOT NULL,
	`nameZh` varchar(255),
	`nameFr` varchar(255),
	`nameJa` varchar(255),
	`taglineEn` varchar(512),
	`taglineZh` varchar(512),
	`taglineFr` varchar(512),
	`taglineJa` varchar(512),
	`descriptionEn` text,
	`descriptionZh` text,
	`descriptionFr` text,
	`descriptionJa` text,
	`category` varchar(64),
	`targetAudienceEn` varchar(512),
	`targetAudienceZh` varchar(512),
	`duration` varchar(64),
	`priceInfo` varchar(128),
	`coverImageUrl` varchar(512),
	`icon` varchar(16),
	`themeColor` varchar(16),
	`highlights` json,
	`isVisible` enum('visible','hidden') NOT NULL DEFAULT 'visible',
	`displayOrder` int NOT NULL DEFAULT 0,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `courses_id` PRIMARY KEY(`id`),
	CONSTRAINT `courses_slug_unique` UNIQUE(`slug`)
);
